//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""actions"",
            ""id"": ""35e2ce81-abc1-40e7-8494-d2885a82ab2e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6a2b733b-cde5-43e9-ad8c-6c72cb2e2c3b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gamepad_Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""91d72b52-0e43-450b-b9a2-51e5680adfca"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDelta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""610c9195-df95-4ddf-9d04-3f27132add90"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse_Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a2f9f9c2-308e-43af-a853-3c060d206453"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Boost"",
                    ""type"": ""Button"",
                    ""id"": ""511da5e6-3ba5-40d3-9072-0d9ee7aa1521"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""e7079d14-1be9-4c0b-8f9f-85c1f3919d30"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleEngines"",
                    ""type"": ""Button"",
                    ""id"": ""10c9dd9b-d8e7-42e0-89f6-b5e6e1e310bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BarrelRoll"",
                    ""type"": ""Button"",
                    ""id"": ""7be3e908-726d-4af8-9f0c-b0ec9cc900bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CenterCrosshair"",
                    ""type"": ""Button"",
                    ""id"": ""721a3e3f-4f33-4e30-93c0-256bf80040ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeView"",
                    ""type"": ""Button"",
                    ""id"": ""341b2690-fe3d-410a-9843-9c57c5fc626f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""8ac1d64a-71ea-4789-bd8c-75e639f547d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnPause"",
                    ""type"": ""Button"",
                    ""id"": ""37580a20-93f1-4046-a6f0-ba8beedd9e69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""663eb51c-f371-4729-8b94-9a38184aaf78"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""28252f98-e575-448b-b227-eb85a85cd542"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ccb1a9af-261b-4fb7-b9f1-8033a2a315a2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fd6fc295-1347-4168-87c3-0214a0d7604b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9b54fa27-2fe9-41db-a6da-052b765eb4f3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""958f4c06-7d0e-463d-bff3-cef716daa8d5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0064c041-7422-4e75-b02e-76030ddf07e4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gamepad_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a84ed91-45c3-4d27-8ff3-7e076f666c2d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6731805-7c99-4143-9852-35866efa5e7e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Boost"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1aea554-b05d-441e-bbea-cf06c0636b01"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""345ea1bf-ae53-4471-94a9-3fbdb38939af"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aebcca0-f105-442e-a7d9-2c5b1bc4192a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleEngines"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""894b3090-3f9c-49ec-9ac0-491d1313ed47"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleEngines"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a6c8fb3-136b-45fc-b0a1-5c3b590d3b52"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BarrelRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57f3380c-92ec-4ad0-b5b4-d97aea8946c9"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BarrelRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""563eb83b-beeb-4bf9-a0ad-66e4768d5f97"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BarrelRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24b4dc68-e9fe-41c5-a5b0-870ba680111c"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CenterCrosshair"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9adf605-e1e8-4ef8-9bd1-3a2b51417c7c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f117af86-9565-44e3-9067-17504f0e1744"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa57f9cb-32c2-494a-9956-a92e0230927b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95dc1996-10b6-48e4-bcea-8a223cf84664"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da527eeb-9aff-4339-955f-837bc1e0aae4"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69181037-482f-4070-9cb7-82de8ae141af"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse_Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""83ce0d54-f0ca-4142-a271-a554d51a19f6"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // actions
        m_actions = asset.FindActionMap("actions", throwIfNotFound: true);
        m_actions_Move = m_actions.FindAction("Move", throwIfNotFound: true);
        m_actions_Gamepad_Aim = m_actions.FindAction("Gamepad_Aim", throwIfNotFound: true);
        m_actions_MouseDelta = m_actions.FindAction("MouseDelta", throwIfNotFound: true);
        m_actions_Mouse_Aim = m_actions.FindAction("Mouse_Aim", throwIfNotFound: true);
        m_actions_Boost = m_actions.FindAction("Boost", throwIfNotFound: true);
        m_actions_Shoot = m_actions.FindAction("Shoot", throwIfNotFound: true);
        m_actions_ToggleEngines = m_actions.FindAction("ToggleEngines", throwIfNotFound: true);
        m_actions_BarrelRoll = m_actions.FindAction("BarrelRoll", throwIfNotFound: true);
        m_actions_CenterCrosshair = m_actions.FindAction("CenterCrosshair", throwIfNotFound: true);
        m_actions_ChangeView = m_actions.FindAction("ChangeView", throwIfNotFound: true);
        m_actions_Pause = m_actions.FindAction("Pause", throwIfNotFound: true);
        m_actions_UnPause = m_actions.FindAction("UnPause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // actions
    private readonly InputActionMap m_actions;
    private IActionsActions m_ActionsActionsCallbackInterface;
    private readonly InputAction m_actions_Move;
    private readonly InputAction m_actions_Gamepad_Aim;
    private readonly InputAction m_actions_MouseDelta;
    private readonly InputAction m_actions_Mouse_Aim;
    private readonly InputAction m_actions_Boost;
    private readonly InputAction m_actions_Shoot;
    private readonly InputAction m_actions_ToggleEngines;
    private readonly InputAction m_actions_BarrelRoll;
    private readonly InputAction m_actions_CenterCrosshair;
    private readonly InputAction m_actions_ChangeView;
    private readonly InputAction m_actions_Pause;
    private readonly InputAction m_actions_UnPause;
    public struct ActionsActions
    {
        private @PlayerInput m_Wrapper;
        public ActionsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_actions_Move;
        public InputAction @Gamepad_Aim => m_Wrapper.m_actions_Gamepad_Aim;
        public InputAction @MouseDelta => m_Wrapper.m_actions_MouseDelta;
        public InputAction @Mouse_Aim => m_Wrapper.m_actions_Mouse_Aim;
        public InputAction @Boost => m_Wrapper.m_actions_Boost;
        public InputAction @Shoot => m_Wrapper.m_actions_Shoot;
        public InputAction @ToggleEngines => m_Wrapper.m_actions_ToggleEngines;
        public InputAction @BarrelRoll => m_Wrapper.m_actions_BarrelRoll;
        public InputAction @CenterCrosshair => m_Wrapper.m_actions_CenterCrosshair;
        public InputAction @ChangeView => m_Wrapper.m_actions_ChangeView;
        public InputAction @Pause => m_Wrapper.m_actions_Pause;
        public InputAction @UnPause => m_Wrapper.m_actions_UnPause;
        public InputActionMap Get() { return m_Wrapper.m_actions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionsActions set) { return set.Get(); }
        public void SetCallbacks(IActionsActions instance)
        {
            if (m_Wrapper.m_ActionsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMove;
                @Gamepad_Aim.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGamepad_Aim;
                @Gamepad_Aim.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGamepad_Aim;
                @Gamepad_Aim.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnGamepad_Aim;
                @MouseDelta.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMouseDelta;
                @MouseDelta.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMouseDelta;
                @Mouse_Aim.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMouse_Aim;
                @Mouse_Aim.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMouse_Aim;
                @Mouse_Aim.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnMouse_Aim;
                @Boost.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnBoost;
                @Boost.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnBoost;
                @Boost.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnBoost;
                @Shoot.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnShoot;
                @ToggleEngines.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnToggleEngines;
                @ToggleEngines.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnToggleEngines;
                @ToggleEngines.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnToggleEngines;
                @BarrelRoll.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnBarrelRoll;
                @BarrelRoll.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnBarrelRoll;
                @BarrelRoll.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnBarrelRoll;
                @CenterCrosshair.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnCenterCrosshair;
                @CenterCrosshair.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnCenterCrosshair;
                @CenterCrosshair.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnCenterCrosshair;
                @ChangeView.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnChangeView;
                @ChangeView.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnChangeView;
                @ChangeView.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnChangeView;
                @Pause.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnPause;
                @UnPause.started -= m_Wrapper.m_ActionsActionsCallbackInterface.OnUnPause;
                @UnPause.performed -= m_Wrapper.m_ActionsActionsCallbackInterface.OnUnPause;
                @UnPause.canceled -= m_Wrapper.m_ActionsActionsCallbackInterface.OnUnPause;
            }
            m_Wrapper.m_ActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Gamepad_Aim.started += instance.OnGamepad_Aim;
                @Gamepad_Aim.performed += instance.OnGamepad_Aim;
                @Gamepad_Aim.canceled += instance.OnGamepad_Aim;
                @MouseDelta.started += instance.OnMouseDelta;
                @MouseDelta.performed += instance.OnMouseDelta;
                @MouseDelta.canceled += instance.OnMouseDelta;
                @Mouse_Aim.started += instance.OnMouse_Aim;
                @Mouse_Aim.performed += instance.OnMouse_Aim;
                @Mouse_Aim.canceled += instance.OnMouse_Aim;
                @Boost.started += instance.OnBoost;
                @Boost.performed += instance.OnBoost;
                @Boost.canceled += instance.OnBoost;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @ToggleEngines.started += instance.OnToggleEngines;
                @ToggleEngines.performed += instance.OnToggleEngines;
                @ToggleEngines.canceled += instance.OnToggleEngines;
                @BarrelRoll.started += instance.OnBarrelRoll;
                @BarrelRoll.performed += instance.OnBarrelRoll;
                @BarrelRoll.canceled += instance.OnBarrelRoll;
                @CenterCrosshair.started += instance.OnCenterCrosshair;
                @CenterCrosshair.performed += instance.OnCenterCrosshair;
                @CenterCrosshair.canceled += instance.OnCenterCrosshair;
                @ChangeView.started += instance.OnChangeView;
                @ChangeView.performed += instance.OnChangeView;
                @ChangeView.canceled += instance.OnChangeView;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @UnPause.started += instance.OnUnPause;
                @UnPause.performed += instance.OnUnPause;
                @UnPause.canceled += instance.OnUnPause;
            }
        }
    }
    public ActionsActions @actions => new ActionsActions(this);
    public interface IActionsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnGamepad_Aim(InputAction.CallbackContext context);
        void OnMouseDelta(InputAction.CallbackContext context);
        void OnMouse_Aim(InputAction.CallbackContext context);
        void OnBoost(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnToggleEngines(InputAction.CallbackContext context);
        void OnBarrelRoll(InputAction.CallbackContext context);
        void OnCenterCrosshair(InputAction.CallbackContext context);
        void OnChangeView(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnUnPause(InputAction.CallbackContext context);
    }
}
